### ISSUE TITLE
2.11.0 version breaks retrocompatibility with python-bigquery 1.x branch

### ISSUE THREAD

**Issue by drake-mer** [googleapis/python-api-core#477] opened 2022-12-06 09:17 UTC
#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-api-core` version: `2.11.0`

#### Steps to reproduce

Run a bigquery job with python-bigquery v 1.28.2 and google-api-core 2.11.0

#### Stack trace
```
TypeError: QueryJob._blocking_poll() got an unexpected keyword argument 'retry'
[...]
    results = query_job.result()  # Waits for job to complete.
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job.py", line 3230, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job.py", line 835, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 256, in result
    self._blocking_poll(timeout=timeout, retry=retry, polling=polling)
```

**Comment by tswast** [comment] 2022-12-14 22:08
I suspect a regression with the functionality related to these PRs:

* https://github.com/googleapis/python-bigquery/pull/41
* https://github.com/googleapis/python-api-core/pull/9

Note that we had to be very careful in #9 to make sure we only passed retry back to `_blocking_poll` if an explicit value for `retry` was passed in. That way that versions of `google-cloud-bigquery` that don't have support for that retry value won't fail.

**Comment by tswast** [comment] 2022-12-14 22:08
There were unit tests to cover this, so I'm not sure what happened.

**Comment by tswast** [comment] 2022-12-14 22:09
I see what happened: https://github.com/googleapis/python-api-core/blob/a152ed60eeb876f9b655716f0d720a85c5680a23/tests/unit/future/test_polling.py#L232

The test intended to not have a `retry` argument. Now has a `retry` argument.

**Comment by vam-google** [comment] 2023-01-09 22:10
This bug should be fixed in python-bigquery instead (please just make it handle non-numeric default value) https://github.com/googleapis/python-api-core/issues/479

**Comment by cristianmtr** [comment] 2023-04-18 10:24
I'm also facing this issue. Are there any workarounds?

**Comment by vchudnov-g** [comment] 2023-10-24 20:43
Support for the BigQuery  v1 branch is ending, as per [this comment](https://github.com/googleapis/python-bigquery/issues/1443#issuecomment-1662634767). Note that the Google OSS Library Breaking Change Policy only provides for a 12-month support window after a new major version of a library is released, and we're beyond that window for BigQuery v1. We encourage you to upgrade to the latest versions of our libraries, and let us know of any problems you encounter.

**Comment by vchudnov-g** [comment] 2023-10-24 20:44
Support for the BigQuery  v1 branch is ending, as per [this comment](https://github.com/googleapis/python-bigquery/issues/1443#issuecomment-1662634767). Note that the Google OSS Library Breaking Change Policy only provides for a 12-month support window after a new major version of a library is released, and we're beyond that window for BigQuery v1. We encourage you to upgrade to the latest versions of our libraries, and let us know of any problems you encounter.

**Closed by vchudnov-g** 2023-10-24 20:44 UTC
Labels: priority: p1
