### ISSUE TITLE
Segmentation Fault When Generating Field Masks For Protos with Optional Fields

### ISSUE THREAD

**Issue by BenRKarl** [googleapis/python-api-core#71] opened 2020-08-12 16:27 UTC
#### Environment details

  - OS type and version: gLinux
  - Python version: 3.7.0
  - pip version: 10.0.1
  - `google-api-core` version: 1.22.1
  - `protoc` version:  3.12.3

#### Steps to reproduce

  1.  Write the following to `foo.proto`:

```
syntax = "proto3";
 
message Nested {
  optional bool test = 1;
}
 
message Foo {
  optional string name = 1;
  Nested nested = 3;
}
```

  2. Compile with `protoc`: `protoc --experimental_allow_proto3_optional --python_out=. foo.proto`

  3. Write the following to `repro.py`:

```py
from foo_pb2 import Foo
from google.api_core import protobuf_helpers
 
foo = Foo()
foo.name = 'name'
foo.nested.test = False
 
field_mask = protobuf_helpers.field_mask(None, foo)
```

#### Code example

```python
# example
```
  4. Install latest `google-api-core`: `python -m pip install google-api-core`
  5. Run: `python repro.py`

#### Stack trace
Using `faulthandler`:

```
Fatal Python error: Segmentation fault

Current thread 0x00007eff5260d180 (most recent call first):
  File "/venvs/simply-local-3.7.0/lib/python3.7/site-packages/google/api_core/protobuf_helpers.py", line 314 in field_mask
  File "repro.py", line 9 in <module>
Segmentation fault
```

**Comment by BenRKarl** [comment] 2020-08-12 16:28
Note also this same behavior occurs with the previous version of `google-api-core`: 1.21.0

**Comment by arithmetic1728** [comment] 2020-08-12 17:24
This is a protoc bug, as suggested by the following program. segv is caused by `foo.Clear` method, which is called by api-core.

```
from foo_pb2 import Foo
 
foo = Foo()
foo.name = 'name'
foo.nested.test = False

foo.Clear()     # <== segv happens here
```

**Comment by arithmetic1728** [comment] 2020-08-12 17:37
Filed an issue to protoc https://github.com/protocolbuffers/protobuf/issues/7801

**Comment by busunkim96** [comment] 2020-08-12 17:42
Closing this issue since the root cause is protobuf itself.

**Closed by busunkim96** 2020-08-12 17:42 UTC

**Comment by BenRKarl** [comment] 2020-08-12 18:09
Thanks @arithmetic1728!
