### ISSUE TITLE
Reduce documentation pipeline delays

### ISSUE THREAD

**Issue by nbro10** [googleapis/python-api-core#553] opened 2023-11-10 12:23 UTC
Basically, similar to my previous issue: https://github.com/googleapis/python-api-core/issues/435

So https://googleapis.dev/python/google-api-core/2.14.0/index.html returns a 404

The version 2.14 has been released, but you forgot to generate the docs, which should have been automatically released using some kind of CD pipeline. 

Thanks.

**Comment by parthea** [comment] 2023-11-10 19:57
Hi @nbro10 , 

Thanks for reporting this issue (again)! The docs are now available at https://googleapis.dev/python/google-api-core/2.14.0/index.html. I've filed an issue internally to follow up on the delay in publishing the docs. (Googlers see b/310241440).

**Comment by parthea** [comment] 2024-01-30 13:00
Thanks for reporting this issue @nbro10. I'm going to re-open this to track improving our documentation pipeline as there are delays.

**Comment by dandhlee** [comment] 2024-01-30 14:23
Hi @nbro10, apologies for this issue. The issue is that it takes time with our newer system to generate these files - it's not that they're forgotten, but they simply take time to be generated. They'll be available within 24 hours - is there a need for this to be expedited faster? The gist of the changes will be available in the changelog.

**Comment by dandhlee** [comment] 2024-01-30 15:08
We unfortunately do have a constraint that restricts us from being able to regenerate them any faster.

Just for my own understandings - Is it possible to point to the latest link instead? Is there a reason why you're looking for the specific versioned link?

**Comment by dandhlee** [comment] 2024-02-05 11:17
Thanks for getting back. I'd advise using `latest` to point to the latest version of the document, and use versioned links only where necessary. If you point to versioned docs that's not latest and the link doesn't work, please feel free to reopen this and/or open a new issue. 

The best we can do right now is have the links available within 24 hours, and regrettably don't have any plans to look into shortening it in the near future. I'll close the issue for now.

**Closed by dandhlee** 2024-02-05 11:17 UTC
Labels: type: docs
