### ISSUE TITLE
Add RefreshError to retryable errors

### ISSUE THREAD

**Issue by baeminbo** [googleapis/python-api-core#312] opened 2021-11-24 15:04 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
`RefreshError` can be raised if GCE metadata server returns 500 error for service account token. But, we currently retry only for `TransportError` at [retry.py](https://github.com/googleapis/python-api-core/blob/v2.2.2/google/api_core/retry.py#L106).

This makes GCP libraries depending on the default retry fail by the transient auth error.

 **Describe the solution you'd like**
Add `auth_exceptions.RefreshError` to `if_transient_error`.

 **Describe alternatives you've considered**
Core API users can use a custom retry that handles `RefreshError` as retryable.

 **Additional context**
See [this screenshot](https://gist.githubusercontent.com/baeminbo/8764d92c01101aa2276e11273fadca7b/raw/e4aae7e369c3d59800cc54ee234aee44ab8d596c/refresh_error.png) of a RefreshError example that happened at GCS API in a Dataflow job.

**Comment by tswast** [comment] 2021-11-30 17:47
Duplicate of https://github.com/googleapis/python-api-core/issues/223 ?

**Comment by baeminbo** [comment] 2021-12-01 00:51
IIUC, #223 is about `Unauthenticated` by 401 from metadata server, which is caused by time sync. But, this is an issue with 500 error from metadata server. So, I think they are different issues.

**Comment by liu-du** [comment] 2022-01-31 00:38
Hi, 

I'm experiencing the same transient issues recently but in my case metadata server returns 404 not found. The error is: 
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=REDACTED&format=full from the Google Compute Engine metadata service. Status: 404 Response:\nb'Not Found\\n'", <google.auth.transport.requests._Response object at 0x7f44b3dcf8d0>)

**Comment by parthea** [comment] 2023-09-01 14:39
Retry logic was added in https://github.com/googleapis/google-auth-library-python/pull/1113. In the case of the 500 errors, there is an open question https://github.com/googleapis/google-auth-library-python/pull/984 requesting more information about how often they are occurring. Please open a new issue in https://github.com/googleapis/google-auth-library-python as that is where the retry logic should be improved.

**Closed by parthea** 2023-09-01 14:39 UTC
Labels: type: feature request
